---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - vpnapp.vpn.io
  resources:
  - vpns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpnapp.vpn.io
  resources:
  - vpns/finalizers
  verbs:
  - update
- apiGroups:
  - vpnapp.vpn.io
  resources:
  - vpns/status
  verbs:
  - get
  - patch
  - update
