apiVersion: v1
kind: Pod
metadata:
  name: wg-client
spec:
  containers:
  - name: wireguard
    image: linuxserver/wireguard
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
          - SYS_MODULE
      privileged: true
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    volumeMounts:
      - name: wg-config
        mountPath: /config/wg0.conf
        subPath: wg0.conf
  volumes:
    - name: wg-config
      secret:
        secretName: dorsinay-wg-conf